name: Auto build
run-name: Auto build

on:
  push:

env:
  MINECRAFT_VERSION: 1.20.4
  VERSION: 1.0.9
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check env
        run: env

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up java development kit
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Give running permission to  Gradle Wrapper
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build mod
        run: ./gradlew clean build

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: AutoBuild_${{ vars.GITHUB_RUN_ID }}
          release_name: AutoBuild-${{ vars.GITHUB_REF_NAME }}-${{ vars.GITHUB_RUN_ID }}-${{ vars.GITHUB_SHA }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /build/libs/TextFileReader-${{ vars.VERSION }}.jar
          asset_name: TextFileReader-${{ vars.VERSION }}-${{ env.MINECRAFT_VERSION }}.jar
          asset_content_type: application/octet-stream

      - name: Upload Release Source Asset
        id: upload-release-src-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /build/libs/TextFileReader-${{ vars.VERSION }}-sources.jar
          asset_name: TextFileReader-${{ vars.VERSION }}-${{ env.MINECRAFT_VERSION }}-sources.jar
          asset_content_type: application/octet-stream